// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeSecurity.Server.Infrastructure.Persistence;

#nullable disable

namespace OfficeSecurity.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260928044325_SoftwareManagement")]
    partial class SoftwareManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("OfficeSecurity.Server.Domain.AccountSetupCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CreatedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RevokedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UsedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash");

                    b.HasIndex("AccountType", "AccountId");

                    b.ToTable("account_setup_codes", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.AdminAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastTotpTimeStep")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockedUntilUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TotpSecretProtected")
                        .HasMaxLength(1024)
                        .HasColumnType("BLOB");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("admin_accounts", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.ApprovedSoftware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("approved_software", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.Computer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("AppliedPolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CertificateExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificatePem")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateRequestPem")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateThumbprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlStatusJson")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DecidedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DecidedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnrollmentCodeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedControls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardwareJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("HeartbeatIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSeenAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSeenIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsEdition")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PollTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("RegisteredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateThumbprint")
                        .IsUnique();

                    b.HasIndex("Hostname");

                    b.HasIndex("PolicyId");

                    b.HasIndex("Status");

                    b.ToTable("computers", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.DeploymentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("ComputerId", "Status");

                    b.ToTable("deployment_jobs", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.DeviceInventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId", "InstanceId")
                        .IsUnique();

                    b.ToTable("device_inventory", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.EnrollmentCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UsedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("enrollment_codes", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.PolicyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasMaxLength(64000)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UpdatedByAdminId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("policies", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.SecurityEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceivedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId", "EventId")
                        .IsUnique();

                    b.HasIndex("ComputerId", "OccurredAtUtc");

                    b.HasIndex("EventType", "OccurredAtUtc");

                    b.ToTable("security_events", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComputerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("PrincipalType", "PrincipalId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.SoftwareInventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("InstallDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ComputerId", "Name", "Version", "Scope")
                        .IsUnique();

                    b.ToTable("software_inventory", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.SoftwarePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowUnsigned")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ApprovedSoftwareId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignerSubject")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SilentArguments")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UploadedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UploadedByAdminId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedSoftwareId");

                    b.ToTable("software_packages", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.SoftwareRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComputerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DecidedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeploymentJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("software_requests", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.StaffAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockedUntilUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmployeeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("NormalizedEmployeeCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("staff_accounts", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.StaffComputerAssignment", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AssignedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AssignedByAdminId")
                        .HasColumnType("TEXT");

                    b.HasKey("StaffId", "ComputerId");

                    b.HasIndex("ComputerId");

                    b.ToTable("staff_computer_assignments", (string)null);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.Computer", b =>
                {
                    b.HasOne("OfficeSecurity.Server.Domain.PolicyDefinition", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.DeploymentJob", b =>
                {
                    b.HasOne("OfficeSecurity.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeSecurity.Server.Domain.SoftwarePackage", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.DeviceInventoryItem", b =>
                {
                    b.HasOne("OfficeSecurity.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.SecurityEvent", b =>
                {
                    b.HasOne("OfficeSecurity.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.SoftwareInventoryItem", b =>
                {
                    b.HasOne("OfficeSecurity.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.SoftwarePackage", b =>
                {
                    b.HasOne("OfficeSecurity.Server.Domain.ApprovedSoftware", null)
                        .WithMany()
                        .HasForeignKey("ApprovedSoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.SoftwareRequest", b =>
                {
                    b.HasOne("OfficeSecurity.Server.Domain.StaffAccount", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeSecurity.Server.Domain.StaffComputerAssignment", b =>
                {
                    b.HasOne("OfficeSecurity.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeSecurity.Server.Domain.StaffAccount", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
