<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1707;CA1515</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Server/OfficeSecurity.Server.Api/OfficeSecurity.Server.Api.csproj" />
    <ProjectReference Include="../../src/Clients/OfficeSecurity.Client.Core/OfficeSecurity.Client.Core.csproj" />
    <ProjectReference Include="../../src/Agent/OfficeSecurity.Agent.Core/OfficeSecurity.Agent.Core.csproj" />
  </ItemGroup>
</Project>
