namespace OfficeSecurity.Contracts;

// ---------------------------------------------------------------- enrollment (anonymous, enrollment code / poll token)

public sealed record HardwareInventory(
    string ComputerName,
    string? OsName,
    string? OsVersion,
    string? OsBuild,
    string? OsEdition,
    string? Manufacturer,
    string? Model,
    string? SerialNumber,
    string? Processor,
    long? MemoryMb,
    long? SystemDiskGb,
    bool? TpmPresent,
    bool? IsDomainJoined,
    string? DomainOrWorkgroup);

public sealed record AgentEnrollRequest(string EnrollmentCode, string CertificateRequestPem, HardwareInventory Hardware);

/// <summary>The poll token proves, until approval, that later status requests come from the same agent.</summary>
public sealed record AgentEnrollResponse(Guid ComputerId, string PollToken);

public sealed record AgentEnrollStatusRequest(Guid ComputerId, string PollToken);

public static class EnrollmentStatuses
{
    public const string PendingApproval = "PendingApproval";
    public const string Approved = "Approved";
    public const string Rejected = "Rejected";
}

/// <param name="Status">One of <see cref="EnrollmentStatuses"/>.</param>
/// <param name="CertificatePem">The computer's client certificate, once approved.</param>
/// <param name="PolicySigningPublicKey">Base64 SubjectPublicKeyInfo of the policy signing key, once approved.</param>
public sealed record AgentEnrollStatusResponse(string Status, string? CertificatePem, string? PolicySigningPublicKey);

// ---------------------------------------------------------------- enrolled agent (mutual TLS)

/// <param name="ParentInstanceId">For USB storage: the USB device it belongs to (what Windows blocks or allows).</param>
public sealed record ConnectedDevice(string InstanceId, string Name, string DeviceClass, string? Manufacturer, string? ParentInstanceId = null);

public sealed record AgentHeartbeatRequest(string AgentVersion, long AppliedPolicyVersion, IReadOnlyList<ControlStatus> Controls, int QueuedEvents);

/// <param name="PendingJobs">Number of approved software installations waiting for this computer.</param>
public sealed record AgentHeartbeatResponse(long LatestPolicyVersion, int HeartbeatIntervalSeconds, int PendingJobs = 0);

/// <param name="Software">Installed programs; null when the agent did not collect them in this report.</param>
public sealed record AgentInventoryRequest(HardwareInventory Hardware, IReadOnlyList<ConnectedDevice> Devices, IReadOnlyList<InstalledSoftware>? Software = null,
    IReadOnlyList<RecoveryKeyReport>? RecoveryKeys = null);

/// <summary>A BitLocker recovery password of one of the computer's drives (sent only over mutual TLS, stored encrypted).</summary>
public sealed record RecoveryKeyReport(string Drive, string ProtectorId, string RecoveryPassword);

/// <param name="Scope">"Machine" (all users) or "User" (installed for one user only).</param>
public sealed record InstalledSoftware(string Name, string? Version, string? Publisher, DateOnly? InstallDate, string Scope);

public static class InstallerTypes
{
    public const string Msi = "Msi";
    public const string Exe = "Exe";
}

/// <summary>An approved installation the agent must perform. The agent verifies the file before running it.</summary>
public sealed record AgentJob(
    Guid JobId,
    string SoftwareName,
    string FileName,
    string Sha256,
    long SizeBytes,
    string InstallerType,
    string? SilentArguments,
    string? SignerSubject,
    bool AllowUnsigned);

public static class JobStatuses
{
    public const string Queued = "Queued";
    public const string Running = "Running";
    public const string Succeeded = "Succeeded";
    public const string SucceededRebootRequired = "SucceededRebootRequired";
    public const string Failed = "Failed";
    public const string Cancelled = "Cancelled";
}

/// <param name="Status">Succeeded, SucceededRebootRequired or Failed.</param>
public sealed record AgentJobResult(string Status, int? ExitCode, string? Message);

public static class EventSeverities
{
    public const string Information = "Information";
    public const string Warning = "Warning";
    public const string Critical = "Critical";
}

/// <param name="EventId">Generated by the agent; makes uploads idempotent when retried after a network failure.</param>
public sealed record AgentEvent(Guid EventId, SecurityEventType Type, string Severity, DateTimeOffset OccurredAtUtc, string? Details);

public sealed record AgentEventsRequest(IReadOnlyList<AgentEvent> Events);

public sealed record AgentEventsResponse(int Accepted);

/// <summary>Short-lived proof, obtained by the agent over mutual TLS, that a staff sign-in happens on this computer.</summary>
public sealed record ComputerLoginTicketResponse(string Ticket, DateTimeOffset ExpiresAtUtc);

// ---------------------------------------------------------------- agent ⇄ staff app on the same computer (named pipe)

public static class AgentLocalProtocol
{
    public const string PipeName = "OfficeSecurityAgent";
    public const string StatusCommand = "status";
    public const string LoginTicketCommand = "login-ticket";

    /// <summary>
    /// Where the installed agent runs from. Only administrators can write there, so the staff application
    /// talks only to a pipe served by this program (protection against a fake agent).
    /// </summary>
    public static string InstalledAgentExecutable() =>
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "OfficeSecurity", "Agent", "OfficeSecurity.Agent.exe");
}

public sealed record AgentLocalRequest(string Command);

/// <param name="State">Agent state, e.g. "Enrolled", "PendingApproval".</param>
/// <param name="CaCertificateBase64">The pinned server CA, so the staff application needs no separate pairing.</param>
public sealed record AgentLocalStatus(string State, Guid? ComputerId, string? ServerAddress, string? CaCertificateBase64, string? Message);

public sealed record AgentLocalResponse(bool Success, AgentLocalStatus? Status, string? LoginTicket, string? Error);
