namespace OfficeSecurity.Contracts;

// ---------------------------------------------------------------- enrollment (anonymous, enrollment code / poll token)

public sealed record HardwareInventory(
    string ComputerName,
    string? OsName,
    string? OsVersion,
    string? OsBuild,
    string? OsEdition,
    string? Manufacturer,
    string? Model,
    string? SerialNumber,
    string? Processor,
    long? MemoryMb,
    long? SystemDiskGb,
    bool? TpmPresent,
    bool? IsDomainJoined,
    string? DomainOrWorkgroup);

public sealed record AgentEnrollRequest(string EnrollmentCode, string CertificateRequestPem, HardwareInventory Hardware);

/// <summary>The poll token proves, until approval, that later status requests come from the same agent.</summary>
public sealed record AgentEnrollResponse(Guid ComputerId, string PollToken);

public sealed record AgentEnrollStatusRequest(Guid ComputerId, string PollToken);

public static class EnrollmentStatuses
{
    public const string PendingApproval = "PendingApproval";
    public const string Approved = "Approved";
    public const string Rejected = "Rejected";
}

/// <param name="Status">One of <see cref="EnrollmentStatuses"/>.</param>
/// <param name="CertificatePem">The computer's client certificate, once approved.</param>
/// <param name="PolicySigningPublicKey">Base64 SubjectPublicKeyInfo of the policy signing key, once approved.</param>
public sealed record AgentEnrollStatusResponse(string Status, string? CertificatePem, string? PolicySigningPublicKey);

// ---------------------------------------------------------------- enrolled agent (mutual TLS)

public sealed record ConnectedDevice(string InstanceId, string Name, string DeviceClass, string? Manufacturer);

public sealed record AgentHeartbeatRequest(string AgentVersion, long AppliedPolicyVersion, IReadOnlyList<ControlStatus> Controls, int QueuedEvents);

public sealed record AgentHeartbeatResponse(long LatestPolicyVersion, int HeartbeatIntervalSeconds);

public sealed record AgentInventoryRequest(HardwareInventory Hardware, IReadOnlyList<ConnectedDevice> Devices);

public static class EventSeverities
{
    public const string Information = "Information";
    public const string Warning = "Warning";
    public const string Critical = "Critical";
}

/// <param name="EventId">Generated by the agent; makes uploads idempotent when retried after a network failure.</param>
public sealed record AgentEvent(Guid EventId, SecurityEventType Type, string Severity, DateTimeOffset OccurredAtUtc, string? Details);

public sealed record AgentEventsRequest(IReadOnlyList<AgentEvent> Events);

public sealed record AgentEventsResponse(int Accepted);

/// <summary>Short-lived proof, obtained by the agent over mutual TLS, that a staff sign-in happens on this computer.</summary>
public sealed record ComputerLoginTicketResponse(string Ticket, DateTimeOffset ExpiresAtUtc);

// ---------------------------------------------------------------- agent ⇄ staff app on the same computer (named pipe)

public static class AgentLocalProtocol
{
    public const string PipeName = "OfficeSecurityAgent";
    public const string StatusCommand = "status";
    public const string LoginTicketCommand = "login-ticket";

    /// <summary>
    /// Where the installed agent runs from. Only administrators can write there, so the staff application
    /// talks only to a pipe served by this program (protection against a fake agent).
    /// </summary>
    public static string InstalledAgentExecutable() =>
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "OfficeSecurity", "Agent", "OfficeSecurity.Agent.exe");
}

public sealed record AgentLocalRequest(string Command);

/// <param name="State">Agent state, e.g. "Enrolled", "PendingApproval".</param>
/// <param name="CaCertificateBase64">The pinned server CA, so the staff application needs no separate pairing.</param>
public sealed record AgentLocalStatus(string State, Guid? ComputerId, string? ServerAddress, string? CaCertificateBase64, string? Message);

public sealed record AgentLocalResponse(bool Success, AgentLocalStatus? Status, string? LoginTicket, string? Error);
